epic: epic/*
task: [ task/*, 'subtask/*' ]
feature: [ 'story/*', 'feature/*' ]
bug: [ 'issue/*', 'fix/*', 'bugfix/*', 'bug/*', 'problem/*', 'hotfix/*', 'defect/*' ]
update: [ 'renovate/*' ]
booking-experience: [ '*/gro-*', '*/grow-*', '*/growth-*', '*/bex-*', '*/bx-*' ]
landing-experience: [ '*/seo-*', '*/lex-*', '*/lx-*' ]
operations: [ '*/ops-*', '*/operations-*', '*/op-*' ]
devops: [ '*/dev-*', '*/devops-*' ]
automerge-merge: [ 'dev' ]
automerge-squash: [ 'issue/*', 'fix/*', 'bugfix/*', 'hotfix/*', 'bug/*', 'problem/*', 'epic/*', 'task/*', 'subtask/*', 'story/*', 'feature/*', 'defect/*', 'dependabot/*', 'revert*' ]
wip: [ 'wip', 'work in progress', 'WIP' ]
